"""add workflow tables

Revision ID: 230439fc292d
Revises: b5bad4ef157e
Create Date: 2025-11-19 11:10:00.513187

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "230439fc292d"
down_revision: str | None = "b5bad4ef157e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Workflow ID（wf_ 前缀）"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="工作流名称"),
        sa.Column("description", sa.Text(), nullable=False, comment="工作流描述"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="工作流状态"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_workflows_created_at", "workflows", ["created_at"], unique=False)
    op.create_index("idx_workflows_status", "workflows", ["status"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Edge ID（edge_ 前缀）"),
        sa.Column("workflow_id", sa.String(length=36), nullable=False, comment="Workflow ID"),
        sa.Column("source_node_id", sa.String(length=36), nullable=False, comment="源节点 ID"),
        sa.Column("target_node_id", sa.String(length=36), nullable=False, comment="目标节点 ID"),
        sa.Column("condition", sa.Text(), nullable=True, comment="条件表达式"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_edges_workflow_id", "edges", ["workflow_id"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Node ID（node_ 前缀）"),
        sa.Column("workflow_id", sa.String(length=36), nullable=False, comment="Workflow ID"),
        sa.Column("type", sa.String(length=20), nullable=False, comment="节点类型"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="节点名称"),
        sa.Column("config", sa.JSON(), nullable=False, comment="节点配置（JSON）"),
        sa.Column("position_x", sa.Float(), nullable=False, comment="节点 X 坐标"),
        sa.Column("position_y", sa.Float(), nullable=False, comment="节点 Y 坐标"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_nodes_workflow_id", "nodes", ["workflow_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_nodes_workflow_id", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("idx_edges_workflow_id", table_name="edges")
    op.drop_table("edges")
    op.drop_index("idx_workflows_status", table_name="workflows")
    op.drop_index("idx_workflows_created_at", table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
