"""Add chat_messages table for workflow conversation history

Revision ID: 2f00b84163ac
Revises: e7d4e8d557ed
Create Date: 2025-11-29 20:06:12.047981

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f00b84163ac"
down_revision: str | None = "e7d4e8d557ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 只创建 chat_messages 表（移除不相关的外键操作以兼容 SQLite）
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Message ID（msg_ 前缀）"),
        sa.Column("workflow_id", sa.String(length=36), nullable=False, comment="关联的工作流 ID"),
        sa.Column("content", sa.Text(), nullable=False, comment="消息内容"),
        sa.Column("is_user", sa.Boolean(), nullable=False, comment="是否为用户消息"),
        sa.Column("timestamp", sa.DateTime(), nullable=False, comment="消息时间戳（UTC）"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_messages_workflow_timestamp",
        "chat_messages",
        ["workflow_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 只删除 chat_messages 表
    op.drop_index("idx_chat_messages_workflow_timestamp", table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
