"""Create agents and runs tables

Revision ID: 5d4dc6e88e12
Revises:
Create Date: 2025-11-16 11:29:04.641919

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d4dc6e88e12"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Agent ID（UUID）"),
        sa.Column("start", sa.Text(), nullable=False, comment="任务起点描述"),
        sa.Column("goal", sa.Text(), nullable=False, comment="任务目的描述"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Agent 状态"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Agent 名称"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_agents_created_at", "agents", ["created_at"], unique=False)
    op.create_index("idx_agents_status", "agents", ["status"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Run ID（UUID）"),
        sa.Column("agent_id", sa.String(length=36), nullable=False, comment="关联的 Agent ID"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Run 状态"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="开始执行时间"),
        sa.Column("finished_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("error", sa.Text(), nullable=True, comment="错误信息"),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_runs_agent_id", "runs", ["agent_id"], unique=False)
    op.create_index("idx_runs_created_at", "runs", ["created_at"], unique=False)
    op.create_index("idx_runs_status", "runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_runs_status", table_name="runs")
    op.drop_index("idx_runs_created_at", table_name="runs")
    op.drop_index("idx_runs_agent_id", table_name="runs")
    op.drop_table("runs")
    op.drop_index("idx_agents_status", table_name="agents")
    op.drop_index("idx_agents_created_at", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
