"""Add tasks table

Revision ID: d8b5f2ee2ca7
Revises: 5d4dc6e88e12
Create Date: 2025-11-16 18:13:35.730389

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8b5f2ee2ca7"
down_revision: str | None = "5d4dc6e88e12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False, comment="Task ID（UUID）"),
        sa.Column("run_id", sa.String(length=36), nullable=False, comment="关联的 Run ID"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Task 名称"),
        sa.Column("input_data", sa.JSON(), nullable=True, comment="输入数据（JSON 格式）"),
        sa.Column("output_data", sa.JSON(), nullable=True, comment="输出数据（JSON 格式）"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Task 状态"),
        sa.Column("error", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("retry_count", sa.Integer(), nullable=False, comment="重试次数"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("started_at", sa.DateTime(), nullable=True, comment="开始执行时间"),
        sa.Column("finished_at", sa.DateTime(), nullable=True, comment="完成时间"),
        sa.Column("events", sa.JSON(), nullable=True, comment="TaskEvent 列表（JSON 格式）"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.create_index("idx_tasks_run_id", "tasks", ["run_id"], unique=False)
    op.create_index("idx_tasks_status", "tasks", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_tasks_status", table_name="tasks")
    op.drop_index("idx_tasks_run_id", table_name="tasks")
    op.drop_index("idx_tasks_created_at", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
