"""Add users table for GitHub OAuth

Revision ID: e7d4e8d557ed
Revises: 73c1a2b4c5d6
Create Date: 2025-11-27 22:05:21.791280

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7d4e8d557ed"
down_revision: str | None = "73c1a2b4c5d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False, comment="User ID（UUID）"),
        sa.Column("github_id", sa.Integer(), nullable=False, comment="GitHub用户ID"),
        sa.Column("github_username", sa.String(length=255), nullable=False, comment="GitHub用户名"),
        sa.Column("github_avatar_url", sa.Text(), nullable=True, comment="GitHub头像URL"),
        sa.Column("github_profile_url", sa.Text(), nullable=True, comment="GitHub个人主页"),
        sa.Column("email", sa.String(length=255), nullable=False, comment="用户邮箱"),
        sa.Column("name", sa.String(length=255), nullable=True, comment="用户姓名"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="是否激活"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="用户角色（user/admin）"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("updated_at", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.Column("last_login_at", sa.DateTime(), nullable=True, comment="最后登录时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("github_id"),
    )
    op.create_index("idx_users_created_at", "users", ["created_at"], unique=False)
    op.create_index("idx_users_email", "users", ["email"], unique=True)
    op.create_index("idx_users_github_id", "users", ["github_id"], unique=True)

    # Drop old tables if they exist
    try:
        op.drop_index(op.f("ix_knowledge_bases_owner_id"), table_name="knowledge_bases")
        op.drop_table("knowledge_bases")
    except:
        pass
    try:
        op.drop_table("foo")
    except:
        pass

    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.String(length=36), nullable=True, comment="创建者ID")
        )
        batch_op.create_foreign_key(
            "fk_tools_user_id", "users", ["user_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.String(length=36), nullable=True, comment="创建者ID")
        )
        batch_op.create_foreign_key(
            "fk_workflows_user_id", "users", ["user_id"], ["id"], ondelete="SET NULL"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_constraint("fk_workflows_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_constraint("fk_tools_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    # Recreate old tables (optional, may not be needed)
    # op.create_table('foo',
    # sa.Column('id', sa.INTEGER(), nullable=True)
    # )
    # op.create_table('knowledge_bases',
    # sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    # sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    # sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    # sa.Column('owner_id', sa.VARCHAR(length=36), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), nullable=False),
    # sa.Column('updated_at', sa.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_knowledge_bases_owner_id'), 'knowledge_bases', ['owner_id'], unique=False)

    op.drop_index("idx_users_github_id", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_created_at", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
